language: java
deploy:
  on:
    branch: develop
  api_key:
    secure: Qhl36sS4iyUVM1SI8sQeA8ZxWjCOAbEF+eTDmBdeYEv9WTdRLfSSFGDsPvvFRIRDHE5zuh2AunUaVG5ilcnhV3xJuIskIyWqAQ9XsJZfHgSjZwaLUi7he2DUoRqSB2NK8wZ1ZyH3bkMCKDplcv5yHrEte1dtJAr9bFX2dsItS92xDpz/RJrtNIDiBuh8+fWpJ5bjdoZu5NYq+zWZT1UkQsqFRmKvchNdbk4ZMNzXQ0pkTdEWfhuPwD+JmeRY9MWFk70KK+2fJozHK2/FsrKJM+482fx/1ZECTUMa0sm8BCNKVq6L6ZW+p1gAKIK+01DjuRjMF6LvW+JCXpWASusGeO7TgVBG8iOXrxD9En1h3fy2djZKnLC9G1ddSrJto4hpHp/WzvyuGRcsxWDAC/SeNEKZVczoPNV+lsrm0xyjLMrVzZpr2H9tEU5HEZY3+Zrak3RUw3wHaPZ6wYEwOy7ywBRbwizLgv0X9kxBLmIgDFEJEgKOKk+dKHAFk5wrySyCXAsJogK2FkuMr4DJjlOH1E/iLXFVfA7UvP/0jJ8EcOXYX5fsJoGSZ6Upp2LzWPwZA943UElzpgiosnH1tlB32nRQlVIe66+GkDOLrIx+DKVnMKTE6kgGcSLUweKbp4x4zHaey9TFo/L7MoKUe13lGgrpNChFfGRIFa6hFqDULvs=
